# Generated by Django 2.0.5 on 2018-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0002_auto_20180516_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
