# Generated by Django 2.0.5 on 2018-05-10 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0003_auto_20180510_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
