# Generated by Django 2.0.5 on 2018-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0003_auto_20180516_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
