# Generated by Django 2.0.5 on 2018-05-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0007_auto_20180510_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
